"""
PolicyLab AI Explanation Domain Models
Defines structured evidence models and grounded explanation outputs.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from .authz import AuthorizationDecision
from .diff import BehavioralTransition


class AIExplanationRequest(BaseModel):
    """
    Structured evidence payload supplied to the AI explanation service.
    Only trusted, structured backend evidence is accepted.
    """
    findingId: str = Field(..., description="Stable finding or counterexample ID, e.g. cx_sc_05")
    scenarioId: str = Field(..., description="Source scenario ID, e.g. sc_05")
    scenarioTitle: Optional[str] = Field(None, description="Scenario title")
    principal: str = Field(..., description='e.g. User::"editor_bob"')
    action: str = Field(..., description='e.g. Action::"delete"')
    resource: str = Field(..., description='e.g. Invoice::"inv_9082"')
    context: Dict[str, Any] = Field(default_factory=dict, description="Authorization context")
    
    baselineDecision: AuthorizationDecision
    candidateDecision: AuthorizationDecision
    transition: BehavioralTransition
    
    determiningPolicies: List[str] = Field(default_factory=list, description="Candidate determining policies")
    baselineDeterminingPolicies: List[str] = Field(default_factory=list)
    
    violatedContractId: Optional[str] = Field(None, description="Violated security contract ID")
    violatedContractTitle: Optional[str] = Field(None, description="Violated security contract title")
    regressionRunId: Optional[str] = Field(None, description="Regression run ID reference")
    
    baselinePolicyText: Optional[str] = Field(None, description="Baseline Cedar policy set (safely delimited)")
    candidatePolicyText: Optional[str] = Field(None, description="Candidate Cedar policy set (safely delimited)")


class AIExplanationResponse(BaseModel):
    """
    Structured, grounded explanation synthesized strictly from the supplied evidence payload.
    """
    findingId: str
    summary: str = Field(..., description="Concise explanation of the observed behavioral change")
    rootCause: str = Field(..., description="Technical explanation of the Cedar policy clause that caused the flip")
    securityRisk: str = Field(..., description="Operational and governance risk of the permission expansion/restriction")
    remediationCedar: str = Field(..., description="Concrete suggested Cedar policy snippet for human review")
    evidenceReferences: List[str] = Field(default_factory=list, description="List of cited evidence IDs verified against input")
    provider: str = Field(default="deterministic-template", description="AI explanation provider name")
    limitations: str = Field(
        default="Explanation is strictly grounded in the supplied structured evidence and bounded by the declared scenario universe. Suggested Cedar modifications require human review and revalidation.",
        description="Transparency statement on AI boundaries"
    )
    generatedAt: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    isFallback: bool = Field(default=False, description="True if generated by deterministic template fallback")
